name: Node.js Backend CI

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
      - run: npm install
      - name: Run tests for Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm test
        working-directory: "backend"
